# Generated by Django 6.0 on 2025-12-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_created_at_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
