# Generated by Django 6.0 on 2025-12-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_title_menu_title_name_alter_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='title_name',
            new_name='app_title',
        ),
    ]
